### PR TITLE
fix: Correctly handle nested lists

### LINKED ISSUE #110: Nested lists throw exception
Sample reproducer:
```
fun `nested lists should work properly`() {
    val schema = KGraphQL.schema {
        query("getNestedList") {
            resolver { -> listOf(listOf("foo", "bar"), listOf("foobar")) }
        }
    }

    val response = deserialize(schema.executeBlocking("{ getNestedList }"))
    println(response)
}
```

Output:

```
Missing selection set on property getNestedList of type List
com.apurebase.kgraphql.ValidationException: Missing selection set on property getNestedList of type List
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnType(RequestInterpreter.kt:133)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleReturnType(RequestInterpreter.kt:118)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.handleSelection(RequestInterpreter.kt:195)
	at com.apurebase.kgraphql.schema.structure.RequestInterpreter.createExecutionPlan(RequestInterpreter.kt:110)
	at com.apurebase.kgraphql.schema.DefaultSchema$execute$2.invokeSuspend(DefaultSchema.kt:65)
```

Expected:

```
{data={getNestedList=[[foo, bar], [foobar]]}}
```

### PR DESCRIPTION
**Pull request by stuebingerb**
Resolves #110 and also fixes a related issue that prevented `null` being passed as value for a nullable list argument.

### CODE REVIEW

File: kgraphql/src/test/kotlin/com/apurebase/kgraphql/specification/typesystem/ListsSpecificationTest.kt [hunk 1]
```diff
@@ -143,7 +144,108 @@ class ListsSpecificationTest {
...
+            schema.executeBlocking("mutation { createNullableList(list: null) { list } }")
+        )
+        assertThat(
+            response.extract<List<*>?>("data/createNullableList/list"),
+            nullValue()
+        )
+    }
+
+    @Test
+    fun `string should not be valid for a nullable list`() {
```
Comment (stuebingerb) [inline kgraphql/src/test/kotlin/com/apurebase/kgraphql/specification/typesystem/ListsSpecificationTest.kt]: Actually... according to https://spec.graphql.org/October2021/#sec-List.Input-Coercion this should be coerced to a list with a single element. 

Maybe I broke that with my error handling improvements but obviously that has never been tested, so it needs to be analyzed in any case. Will have a look.
