### PR TITLE
fix: Fix non-nullable union types

### LINKED ISSUE #135: Incorrect non-null handling for union types
See `SchemaPrinterTest#schema with union types should be printed as expected`.

The schema is defined with a union property "pdf" that cannot return `null`:
```
val linked = unionType("Linked") {
    type<Author>()
    type<Scenario>()
}

type<Scenario> {
    unionProperty("pdf") {
        returnType = linked
        resolver { scenario: Scenario ->
            if (scenario.author.startsWith("Gamil")) {
                Scenario("gambino", "nope")
            } else {
                Author("Chance", emptyList())
            }
        }
    }
}
```

However, the corresponding SDL prints it as `Linked`, i.e. nullable:
```
type Scenario {
  author: String!
  content: String!
  pdf: Linked
}
```

The root cause seems to be that union types for unknown reasons are not wrapped in NON_NULL as all others. Probably affects lists of union types as well.

### PR DESCRIPTION
**Pull request by stuebingerb**
Resolves #135

### CODE REVIEW

File: kgraphql/src/test/kotlin/com/apurebase/kgraphql/schema/SchemaPrinterTest.kt [hunk 1]
```diff
@@ -112,6 +112,12 @@ class SchemaPrinterTest {
                         }
                     }
                 }
+                unionProperty("nullablePdf") {
+                    returnType = linked
+                    nullable = true
```
Comment (stuebingerb) [inline kgraphql/src/test/kotlin/com/apurebase/kgraphql/schema/SchemaPrinterTest.kt:117]: Would be good to read nullability (and also iterability) from the actual type but with the current implementation it is hard (if not impossible) to do so. As of now there doesn't seem to be a way to define a union property of lists for a non-sealed class.
