### PR TITLE
fix: fix incorrect descriptions in SDL

### LINKED ISSUE #413: SchemaPrinter creates invalid SDL with descriptions enabled
When printing a schema with multi-line string descriptions, an invalid SDL is generated:

```
type Mutation {
  "Add a test object"
  "With some multi-line description"
  "(& special characters like " and \n)"
  addObject(toAdd: TestObjectInput!): TestObject!
}
```

This causes validation errors in https://www.leskoff.com/s01929-0 and also in our own parser:

```
com.apurebase.kgraphql.InvalidSyntaxException: Syntax Error: Expected Name, found String "With some multi-line description".
```

Correct would be the use of multi-line strings, i.e.

```
type Mutation {
  """
  Add a test object
  With some multi-line description
  (& special characters like " and \n)
  """
  addObject(toAdd: TestObjectInput!): TestObject!
}
```

### LINKED ISSUE #414: SchemaPrinter creates invalid SDL with descriptions enabled
When printing a schema with descriptions enabled, SchemaPrinter also includes a description for the root operation types:

```
schema {
  "Query object"
  query: Query
  "Mutation object"
  mutation: Mutation
  "Subscription object"
  subscription: Subscription
}
```

This causes validation errors in https://www.leskoff.com/s01929-0 and also in our own parser:

```
com.apurebase.kgraphql.InvalidSyntaxException: Syntax Error: Expected Name, found String "Query object".
```

[According to the spec](https://spec.graphql.org/draft/#RootOperationTypeDefinition), root operation types do not support descriptions:

Image

This bug might not apply to SDL only, I would expect that root operation types also do not support descriptions via our DSL.

### PR DESCRIPTION
**Pull request by stuebingerb**
Resolves #413
Resolves #414

### CODE REVIEW

File: kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/SchemaPrinter.kt [hunk 1]
```diff
@@ -247,8 +245,19 @@ class SchemaPrinter(private val config: SchemaPrinterConfig = SchemaPrinterConfi
     // https://spec.graphql.org/October2021/#sec-Descriptions
     private fun StringBuilder.appendDescription(type: Any, indentation: String = ""): StringBuilder {
         type.description()?.takeIf { config.includeDescriptions }?.let { description ->
-            description.forEach {
-                appendLine("$indentation\"$it\"")
+            if (description.size == 1) {
+                // We could use block strings here as well but opt to use a single line for readability. We have to
```
Comment (stuebingerb) [inline kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/SchemaPrinter.kt]: Open for discussion. We could also

1. Always use block strings for descriptions, or
2. Use block strings if the description contains special characters (including line breaks)

Comment (mervyn-mccreight) [reply kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/SchemaPrinter.kt]: I'd go for 2 for simplicity reasons. Would it look ugly?

Comment (stuebingerb) [reply kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/SchemaPrinter.kt]: I don't think it would look more ugly than a regular string with lots of escaped characters. Probably even more readable, will change.

**Review by mervyn-mccreight — APPROVED** [review]
