### PR TITLE
fix!: Limit built-in scalars to the ones defined by the spec

### LINKED ISSUE #83: Incorrect built-in scalars
KGraphQL currently defines the following [built-in scalars](https://github.com/stuebingerb/KGraphQL/blob/0.22.0/kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/builtin/BUILT_IN_TYPE.kt#L38-L55):

```
STRING
SHORT
INT
DOUBLE
FLOAT
BOOLEAN
LONG
```

However, [the spec](https://spec.graphql.org/draft/#sec-Scalars.Built-in-Scalars) defines the following:
```
Int, Float, String, Boolean, and ID
```

According to the spec, those must be supported and also behave in a special way during introspection (which likely is not correctly implemented either).

So:

- ID has to be added (cf. https://github.com/aPureBase/KGraphQL/issues/173)
- Short and Long have to be removed
- Handling of built-in types in Introspection needs to be analyzed and fixed if needed

IMHO, Short and Long can still be included as built-in "extended" types to save users of the library from having to define them on their own but they must not behave like GraphQL built-in types. We can then also think about adding other common JVM types to those extended built-ins.

### PR DESCRIPTION
**Pull request by stuebingerb**
Partially resolves #83 by splitting up the current `BuiltInScalars` into two:

- The actual built-in scalars as defined by the spec
- Some extended scalars supported by KGraphQL

BREAKING CHANGE: Those extended scalars are no longer automatically added to a schema but must be manually included using `extendedScalars()` if needed.

BREAKING CHANGE: Shorts are returned as numeric value, no longer as string.

### CODE REVIEW

File: kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/dsl/SchemaBuilder.kt [hunk 1]
```diff
@@ -140,6 +141,12 @@ class SchemaBuilder internal constructor() {
         booleanScalar(T::class, block)
     }
 
+    fun extendedScalars() {
```
Comment (mervyn-mccreight) [inline kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/dsl/SchemaBuilder.kt:144]: Are there tests specifying that with not invoking this, the additional scalars are not present?

Comment (stuebingerb) [reply kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/dsl/SchemaBuilder.kt:144]: I've seen all tests fail that I adjusted but it would make sense to have it validated explicitly. Will update but I have found some strange behavior with the implemented coercions that I want to analyze first.

Comment (stuebingerb) [reply kgraphql/src/main/kotlin/com/apurebase/kgraphql/schema/dsl/SchemaBuilder.kt:144]: This looks more complicated: #160

But I have at least added some validation

File: kgraphql/src/test/kotlin/com/apurebase/kgraphql/specification/typesystem/ScalarsSpecificationTest.kt [hunk 2]
```diff
@@ -21,6 +22,71 @@ import java.util.UUID
...
+            }
+            query("boolean") {
+                resolver<Boolean> { true }
+            }
+            // TODO: ID, cf. https://github.com/stuebingerb/KGraphQL/issues/83
+        }
+
+        val response = deserialize(schema.executeBlocking("{ int float double string boolean }"))
+        assertThat(response.extract<Int>("data/int"), equalTo(1))
+        assertThat(response.extract<Float>("data/float"), equalTo(2.0))
```
Comment (stuebingerb) [inline kgraphql/src/test/kotlin/com/apurebase/kgraphql/specification/typesystem/ScalarsSpecificationTest.kt:48]: IMHO this should be `equalTo(2.0f)` but haven't found out why that doesn't work.

File: kgraphql/src/test/kotlin/com/apurebase/kgraphql/specification/typesystem/ScalarsSpecificationTest.kt [hunk 3]
```diff
@@ -21,6 +22,71 @@ import java.util.UUID
...
+                resolver<Long> { Long.MAX_VALUE }
+            }
+            query("short") {
+                resolver<Short> { 2.toShort() }
+            }
+        }
+
+        val response = deserialize(schema.executeBlocking("{ long short }"))
+        assertThat(response.extract<Long>("data/long"), equalTo(9223372036854775807L))
+        assertThat(response.extract<Int>("data/short"), equalTo(2))
```
Comment (stuebingerb) [inline kgraphql/src/test/kotlin/com/apurebase/kgraphql/specification/typesystem/ScalarsSpecificationTest.kt:87]: IMHO this should be `extract<Short>` and `equalTo(2.toShort())` but haven't found out why that doesn't work. There is also a cast in `TestUtils.extract` that apparently successfully casts an `Int` to a `Short`, which shouldn't be possible. Hopefully that will all become clearer during work on #160.

**Review by mervyn-mccreight — APPROVED** [review]
